name: mysql

on:
  push:

jobs:
  job-with-mysql-8_0:
    runs-on: ubuntu-20.04
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: django_db
          MYSQL_USER: django_user
          MYSQL_PASSWORD: pa$$word
    steps:
      - name: Show Docker containers
        run: docker ps -a
