name: Create MySQL DB, User, and Permissions

on:
  push:
    branches:
      - master

jobs:
  create-mysql-db-user:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MySQL
        uses: pullreminders/setup-mysql@v1
        with:
          mysql-version: '8.0'
        
      - name: Create MySQL DB, User, and Permissions
        run: |
          mysql -h localhost -e "CREATE DATABASE IF NOT EXISTS akhil;
          CREATE USER 'new_user'@'localhost' IDENTIFIED BY 'password';
          GRANT ALL PRIVILEGES ON database_name.* TO 'new_user'@'localhost';"
