name: MySQL Docker

on: [push]

jobs:
  mysql:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
          MYSQL_DATABASE: testdb
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v2


    - name: Create MySQL user and grant permissions
      run: |
        mysql -h127.0.0.1 -uroot testdb -e "CREATE USER 'your_username'@'%' IDENTIFIED BY 'your_password';"
        mysql -h127.0.0.1 -uroot testdb -e "GRANT ALL PRIVILEGES ON testdb.* TO 'your_username'@'%';"
        mysql -h127.0.0.1 -uroot testdb -e "FLUSH PRIVILEGES;"
     
