name: MySQL Setup

on:
  push:
    branches:
      - master

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    steps:
    - name: Set up MySQL
      run: |
        sudo apt-get update
        sudo apt-get install -y mysql-server

        # Start MySQL service
        sudo service mysql start

        # Set the root password for MySQL (replace YourRootPassword with your desired root password)
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY 'YourRootPassword'"

        # Create a new MySQL user and database
        sudo mysql -e "CREATE DATABASE YourDatabaseName"
        sudo mysql -e "CREATE USER 'YourUsername'@'localhost' IDENTIFIED BY 'YourPassword'"
        sudo mysql -e "GRANT ALL PRIVILEGES ON YourDatabaseName.* TO 'YourUsername'@'localhost'"
        sudo mysql -e "FLUSH PRIVILEGES"

        # Optional: Output MySQL version for verification
        mysql --version

      env:
        YourRootPassword: YourDesiredRootPassword
        YourUsername: YourDesiredUsername
        YourDatabaseName: YourDesiredDatabaseName
